feat: updated meteor light palette
Simspace/monorail pull request #191
Opened 2024-05-07 16:45 UTC by jakeaustinlewis

[CFP-2710](https://resolvn.atlassian.net/browse/CFP-2710)

This PR updates Meteor light theme's design tokens.

Raw colors
Alias tokens
Action tokens

2024-05-07 18:32 UTC, hfreund requested changes

2024-05-07 18:32 UTC, hfreund commented on packages/themes/src/meteor/theme/light.ts
>    GreyA900 = '#181621',
@jakeaustinlewis are these tokens used anywhere? If not, should we remove them?

2024-05-07 18:32 UTC, hfreund commented on packages/themes/src/meteor/theme/light.ts
>    Yellow500 = '#FFD570',
@jakeaustinlewis I think the ramp values are off for 100 - 500
```
"Warning": {
    "100": {
      "type": "color",
      "value": "#fff4db"
    },
    "200": {
      "type": "color",
      "value": "#ffecbf"
    },
    "300": {
      "type": "color",
      "value": "#ffe29c"
    },
    "400": {
      "type": "color",
      "value": "#ffd570"
    },
    "500": {
      "type": "color",
      "value": "#ffc53c"
    },
    ```

2024-05-07 18:32 UTC, hfreund commented on packages/themes/src/meteor/theme/light.ts
>    Active = 0.12,
`Active` and `Focus` should both be `0.16` (same as dark mode)

2024-05-07 18:32 UTC, hfreund commented on packages/themes/src/meteor/theme/light.ts
>      focusRing: {
@jakeaustinlewis I think the focus ring needs to be updated for all colors (as it was in dark mode)
```
focusRing: {
    inner: RawColor.Blue600,
    outer: RawColor.Blue300
},
```

2024-05-07 19:16 UTC, jakeaustinlewis commented on packages/themes/src/meteor/theme/light.ts
>    Active = 0.12,
@hfreund The figma file says:

```
Other/Hover (4%)
Other/Selected (8%)
Other/Active (12%)
Other /Focus (12%)
```

Is this the source of truth? Are these values outdated?

2024-05-07 19:22 UTC, jakeaustinlewis commented on packages/themes/src/meteor/theme/light.ts
>    GreyA900 = '#181621',
These are not used anywhere. I was a little scared to remove them since we don't have tests, but I can remove them!

2024-05-07 19:24 UTC, jakeaustinlewis commented on packages/themes/src/meteor/theme/light.ts
>    Yellow500 = '#FFD570',
Whoops, missed this 👍

2024-05-07 19:26 UTC, gsamaniego41 approved these changes
Code LGTM!

2024-05-07 19:36 UTC, hfreund commented on packages/themes/src/meteor/theme/light.ts
>    Active = 0.12,
Ah I didn't realize they were written in text. Those are some visual references for UX, but they aren't actually tied to code. I also failed to update this text when I changed the values...

Anyway, thats why I included the JSON files with the exported values that **are** correct https://www.notion.so/Dark-Mode-Updates-3ada6d9a3ddd4d72b7fab780ec8f1a4d?d=8bc29135921a4659bd28e2da235c95ce&pvs=4#c9553b54aebf49ab98624bc01b7c85d1

2024-05-08 13:34 UTC, hfreund commented on packages/themes/src/meteor/theme/light.ts
> +  Yellow100 = '#fff4db',
@jakeaustinlewis does this want to be capitalized too?

2024-05-08 13:36 UTC, hfreund approved these changes

2024-05-08 18:14 UTC, merged