feat: meteor alert style updates
Simspace/monorail pull request #198
Opened 2024-05-17 20:52 UTC by gsamaniego41

2024-05-20 16:45 UTC, gsamaniego41 commented on packages/components/src/TextAlert/TextAlert.tsx
> +export const TextAlert = React.forwardRef((inProps, ref) => {
Needs UX input: Should `TextAlert` accept an alert title, action buttons, or be dismissible (onClose)?

2024-05-21 19:19 UTC, hfreund requested changes

2024-05-21 19:19 UTC, hfreund commented on packages/storybook/src/Alert/Alert.stories.tsx
> +          </Alert>
@gsamaniego41 the `Alert.text` variant should use the same color tokens as the alert type:
`error.lowEmphasis.contrastText`
`warning.lowEmphasis.contrastText`
`info.lowEmphasis.contrastText`
`success.lowEmphasis.contrastText`

2024-05-22 16:36 UTC, hfreund approved these changes

2024-05-22 20:07 UTC, jakeaustinlewis approved these changes
LGTM!

2024-05-22 20:30 UTC, merged