[CFP-2878] feat: new Theme - Legacy with Plex
Simspace/monorail pull request #209
Opened 2024-06-07 14:58 UTC by jakeaustinlewis

2024-06-07 20:04 UTC, hfreund commented on packages/themes/src/legacyPlex/theme/baseTheme.ts
> +        fontWeight: FontWeight.Bold,
@jakeaustinlewis this should be Medium

2024-06-07 21:06 UTC, 0x706b commented on packages/themes/src/legacyPlex/theme/themeComponents.ts
> +// eslint-disable-next-line no-restricted-imports
Since this theme is just the legacy theme with plex, you can just use the legacy theme's `themeComponents` instead of copying it all into a new file

2024-06-10 14:33 UTC, jakeaustinlewis commented on packages/themes/src/legacyPlex/theme/themeComponents.ts
> +// eslint-disable-next-line no-restricted-imports
Oh true. Thanks Peter!

2024-06-10 15:02 UTC, dlosorioa requested changes
Couple of font weight look off, when compared to the design. Please update the suggestions

2024-06-10 15:36 UTC, jakeaustinlewis commented on packages/themes/src/legacyPlex/theme/baseTheme.ts
> +        fontWeight: FontWeight.Medium,
@dlosorioa 
![image](https://github.com/Simspace/monorail/assets/8593029/e2c70da1-b892-45bf-912b-92f6c373ae92)

Looks like the json doc that was provided has subtitle2 with a fontWeight of Medium

2024-06-10 15:50 UTC, gsamaniego41 approved these changes

2024-06-10 16:06 UTC, jakeaustinlewis commented on packages/themes/src/legacyPlex/theme/baseTheme.ts
> +        fontWeight: FontWeight.Medium,
I updated the Subtitle2 fontWeight to `SemiBold` 👍

2024-06-10 17:20 UTC, merged