[NG-1618] Icon fixes
Simspace/monorail pull request #240
Opened 2024-12-26 22:30 UTC by juliangarciasim

# Summary

The icon size for the meteor theme was slightly bigger than what we have on the designs

2025-01-06 18:49 UTC, 0x706b approved these changes

2025-01-06 19:13 UTC, reedhamilton approved these changes

2025-01-08 16:18 UTC, 0x706b commented on packages/themes/src/meteor/components/SvgIcon/themeOverrides.ts
> +import type { Components, Theme } from '@mui/material'
A new version of `@monorail/themes` will need to be published

2025-01-08 16:19 UTC, 0x706b requested changes

2025-01-08 16:19 UTC, 0x706b commented on packages/themes/src/meteor/components/SvgIcon/themeOverrides.ts
> +import type { Components, Theme } from '@mui/material'
A new version of `@monorail/themes` will need to be published

2025-01-13 21:53 UTC, 0x706b approved these changes

2025-01-14 03:06 UTC, merged